version: '3'

services:
  php:
    container_name: script
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    
  sql:
    container_name: sql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phplogin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql